### PR TITLE
Prevent unnecessary CI builds

### PR DESCRIPTION
**Pull request by shadowofsilicon**
This adds a commit filter to AppVeyor.  The files that match this filter will not trigger a build.

Excluded:
all files ending in .md
all files ending in .yml
everything in the `docs` directory
the EULA
all hidden files

For example, this PR should not trigger a AppVeyor build.

### CODE REVIEW

**Comment by retailcoder** [comment]
OMG YOU'RE MY HERO!!!!!!

**Comment by shadowofsilicon** [comment]
Really?  All my heroes know how to use Git... stupid branching synchronizing wtf...

**Comment by Vogel612** [comment]
I'm pretty sure that was retailcoder not knowing how to use git.... #justsayin 😉

**Comment by shadowofsilicon** [comment]
no, I'm talking about the yellow status of this PR, its b/c my branch isn't synced with upstream before I submitted this PR

**Comment by Vogel612** [comment]
no, that's because AppVeyor is not building your PR AFAICT

**Comment by shadowofsilicon** [comment]
Hmm... I tested with my AppVeyor account and AFAICT it worked; but this PR is also pulling all my previous commits, so I guess we'll have to wait to see if this actually works

**Comment by retailcoder** [comment]
@shadowofsilicon I think it's the "squash & merge" commit that you hadn't pulled that brought all these commits back. no biggie.

**Pull request merged**
