### PR TITLE
Standardized Reparsing from Code Explorer and Inspection Results toolwindows

### PR DESCRIPTION
**Pull request by retailcoder**
This PR potentially fixes a number of pending issues, by skipping the loading of type library `Rubberduck.tlb` (using GUID:{E07C841C-14B4-4890-83E9-8C80B06DD59D}) which has been seen "stalling' the *loading references* parser state; logging any ther type loader errors, so failing at that step shouldn't stall the parser state on "loading referenes" anymore.

The 'Refresh' command in Code Explorer and Inspection Results toolwindows now behaves more instinctively; also adjusted "busy" state in inspection results.

### CODE REVIEW

**Comment by retailcoder** [comment]
I hate that this means `Rubberduck.AssertClass` becomes an unresolvable type.

**Comment by retailcoder** [comment]
ref. #2351, #2352

**Comment by Vogel612** [comment]
FWIW I'm not sure we need to generally skip Rubberduck.tlb ... We just need to be able to skip it **in case** it blows. If it's stalling (aka. not terminating) we could associate type-retrieval with a timeout instead. This might resolve the issues without making Rubberduck.AssertClass unresolvable by default

**Comment by retailcoder** [comment]
@Vogel612 agreed. I think the skipping was just plain overboard, I don't see how it could blow up now that it's wrapped in a try/catch that logs it. I'll double-check to be sure the library isn't deemed loaded when it isn't (so we have a shot at retrying), and make another PR.

**Pull request merged**
