### PR TITLE
Issue #5723

### PR DESCRIPTION
**Pull request by GmausDev**
I´ve been added the required information. I hope its fine.

### CODE REVIEW

**Comment by retailcoder** [comment]
I've converted this PR to "draft", since it's a work-in-progress - don't hesitate to ask any questions, we're very happy to help!

**Comment by GmausDev** [comment]
I renamed all the references, also added the undefined

**Comment by GmausDev** [comment]
It´s okay?

**Comment by Vogel612** [comment]
As it is, this is only a partial fix to the changes suggested in the original issue. As it is, this is perfectly ready to merge, though.

The current state does not include the proposed "new" inspection types or the configuration reader handling that sets the inspection types to use the introduced "Uncategorized" value.

I vote in favor of accepting this PR as is and leaving the reviewing (and recategorizing) to someone in the core team

**Comment by retailcoder** [comment]
Absolutely no problem at all, no worries!

**Pull request merged**
