### PR TITLE
AboutControl Dynamic

### PR DESCRIPTION
**Pull request by GmausDev**
#5451  First form fixed.

I search all System Color references and transform to Dynamic.

### CODE REVIEW

**Review by Vogel612 — APPROVED** [review]

**Comment by GmausDev** [comment]
@Vogel612  It´s huge the quantity of forms , u prefer PR by PR or commit by commit in the same PR?

**Comment by GmausDev** [comment]
ATM I´ll send in another PR my bad

**Comment by retailcoder** [comment]
> u prefer PR by PR or commit by commit in the same PR?

Since they're essentially single-file, single-commit PRs, I think it's safe to combine them.

**Comment by GmausDev** [comment]
@retailcoder ´Kay done at #6038

**Pull request merged**
