### PR TITLE
Integrate annotations into parse tree

### PR DESCRIPTION
**Pull request by autoboosh**
Here's the next try to get the annotations into the parse tree, sorry for the delay.

This PR does two things:
1. Integrate annotations into parse tree
2. Replace comment parsing with IAnnotation instances

The testing infrastructure still uses their own attribute concepts. Since that would have been another big change I left it as is and concentrated on the core.

Annotations still have the same limitations as before, i.e. only one annotation above a method is allowed. Also, no annotations are allowed on the same line. The grammar does allow annotations on the same line, but the existing code does not consider this yet.

Please let me know if there's anything that should be changed.

### CODE REVIEW

**Comment by retailcoder** [comment]
The current implementation supports multiple `@Ignore` annotations; the "ignore once" quickfix appends the inspection's `AnnotationName` to a list of annotations on the line right above a declaration or identifier reference - how does this PR interact with "ignore once"?

**Comment by autoboosh** [comment]
That's a bug. The current annotation grammar only allows arguments to be separated by comma. The ignore quick fix assumed that the argument separator was a whitespace.

Should we change the grammar to allow arguments to be separated by whitespace?

Right now this is not valid:

`'@Ignore Inspection1 Inspection2`

The correct way to separate arguments is now:

`'@Ignore Inspection1, Inspection2`

**Comment by retailcoder** [comment]
Not a problem - we'll change the quickfix to include a comma

**Comment by autoboosh** [comment]
OK. It's already changed here: https://github.com/rubberduck-vba/Rubberduck/pull/1316/commits/6a9bf51e94605f4002820597cd4cd6cef8e1a5c6.

Changing to whitespace separators shouldn't be a big problem if we ever want to do that though.

**Comment by retailcoder** [comment]
Looks rock-solid, great work!

**Pull request merged**
