### PR TITLE
Enabled automatic horizontal scrollbar for the Test Explorer window.

### LINKED ISSUE #5133: Horizontal scroll bar in the test explorer
There is currently no horizontal scrollbar in the test explorer. This is somewhat inconvenient as the test explorer rows tend to be pretty wide due to all of the information when quite often what you want to see on top of which test is failing is the message which is all the way to the left.

At the moment I have it docked normally, but have to undock it if a test fails and I have to inspect the message as there is no way to scroll to the left to read it.

### PR DESCRIPTION
**Pull request by glowingrunes**
Enabled a horizontal scrollbar to appear automatically when the window size is decreased for the Test Explorer.

Closes #5133.

### CODE REVIEW

**Comment by glowingrunes** [comment]
An issue was raised after the previous scrollbar for the Code Inspection window was added in by me. I've done a fix for it now (going to make a new pull request which will close the issue, #5237) and I'm going to update this pull request with the fix as well. Sorry about that!

**Comment by bclothier** [comment]
I'm a bit confused here. The linked issue #5237 is for code inspection toolwindow but this seems to fix test explorer toolwindow?

Wouldn't we want the fix to be applied on all toolwindow to have an uniform behavior WRT sizing & scrolling?

**Comment by glowingrunes** [comment]
There were 2 issues, #5133 and #5135, which were to add a horizontal scrollbar to the Test Explorer and Code Inspections window, respectively. I added similar code to both, so I thought it best to add the fix for #5237 not only to the Code Inspection window but the Test Explorer as well. My pull request for #5133 had already been merged in, so I updated my pull request for #5135 which is still pending.

I'm still new to Rubberduck, so if you could give me a list of the other tool windows that require these changes then I can open a new issue and add the same behaviour to them too.

**Comment by bclothier** [comment]
We have 4 toolwindows:

Code Explorer
Todo Explorer
Test Explorer
Code Inspection Results

We have few more XAML dialogs (e.g. Settings, RegEx Assistant) but they aren't used in a toolwindow so I think they don't necessarily need the same behavior.

**Comment by glowingrunes** [comment]
Hi, are you able to get this pull request approved so it counts towards my Hacktoberfest PRs please?

**Comment by MDoerner** [comment]
It should count anyway as long as we do not tag it as spam.

**Comment by glowingrunes** [comment]
Oh right, I misunderstood the rules on the Hacktoberfest website when it said PRs have to "successfully pass the review period" before they'll become valid. Thought it meant it had to be reviewed and merged in the repo, not go through the Hacktoberfest 7-day review period. My bad! Thanks :)

**Pull request merged**
