### PR TITLE
[WIP] Permissive assert

### PR DESCRIPTION
**Pull request by Vogel612**
The changes to project files were done by monodevelop. As such I can roll them back at any time and subsequently ignore the changes. 

I'm very interested in having unit-tests run, since an error in overload-handling for `Application.Run` (only visible in `WordApp` and `AccessApp`) prevents me from testing this on my dev machine.

Comments on the type-promotions performed are very welcome. 

Sidenote: I changed some lines in other .cs files which were marked as compiler errors by mono. Additionally I added the key `Language_JP` to the english resx file.

### CODE REVIEW

**Comment by retailcoder** [comment]
Ooh nice! :+1:

**Comment by ckuhn203** [comment]
Shiny.

**Comment by Vogel612** [comment]
As mentioned in chat already: I can unfortunately not open the Rubberduck.Tests Project on my development machine :sob: As such I'd love to write unit-tests, but cannot. I also cannot execute those that exist, because Mono doesn't compile this correctly...

As such this is not a Task I can really do work on from here on out. @retailcoder @ckuhn203 ideas?

**Comment by retailcoder** [comment]
All good. I'll merge it in and pick up from there :-)

**Pull request merged**
