### PR TITLE
Italian translation for stable release

### PR DESCRIPTION
**Pull request by PhilCattivocaratere**
It should be complete.

### CODE REVIEW

**Comment by PhilCattivocaratere** [comment]
Mmmm... AppVeyor does not agree with me. I will investigate.

**Comment by Vogel612** [comment]
as far as I can tell, the AppVeyor failure is completely unrelated to the changes in this PR. I restarted the job to check whether the issue remains, but the error message suggests that we're running into issues with the SDK we're using to specify our project setup.

**Comment by Vogel612** [comment]
@bclothier has correctly suggested that this PR is based on a comparatively old version (from August 2020) of the `next` branch. That version includes an old specification in the Project declaration which is no longer supported. 

@PhilCattivocaratere could you try updating your branch with the latest changes from `next`?

**Comment by PhilCattivocaratere** [comment]
> @PhilCattivocaratere could you try updating your branch with the latest changes from `next`?
Thank you for your intetest. I was testing on my pc and everything was ok.
My knowledge is... ehm... low. What should I take from `next` and insert in my brench?

**Comment by retailcoder** [comment]
The PR is based off the `main` branch, that's why it's so many commits behind `next`.

Let's use git to fix this.

First let's checkout the *next* branch:

```
git checkout next
```

Now let's bring in everything that was merged into it since the fork (or since the last pull):

```
git pull upstream next
```

Now the *next* branch is up-to-date, let's branch off here:

```
git checkout -b translations
```

We're now in a new branch; let's add the commit with the aptly named `cherry-pick` command:

```
git cherry-pick 8c5d27d
```

Now if all goes well there aren't any conflicts to resolve and we can push the branch to GitHub:

```
git push origin/translations
```
Now opening a pull request to merge /translations into /next would only include the merge commit and the cherry-picked 8c5d27d commit.

@Vogel612 did I get everything right?

**Comment by retailcoder** [comment]
Closing *this* PR, because you don't want to be doing the 400+ commit merge to *main* 😊

**Comment by MDoerner** [comment]
Actually, the desired effect can probably be obtained by rebasing the translation branch on `next`, i.e.

```
git rebase next
```
while the translation branch is checked out or
```
git rebase next ItalianTranslations
```
while it is not checked out. Since there are only file additions and additions to files not otherwise changes, there should be no conflicts while rebasing.
I think that is simpler than the cherry picking.

**Pull request closed without merging**
