### PR TITLE
MoveMember Refactoring

### LINKED ISSUE #2452: Feature Request: Refactor, move Sub/Function to different module
Would it be possible to have a refactor option that allows moving a sub or function to a different module and updating the function calls to that procedure, such that they match the new module?

For example, module Foo has sub Bar and is used as: Foo.Bar. Now, Bar is being moved to module FooBar and should be called as FooBar.Bar.

### LINKED ISSUE #3618: "Move Members" refactoring
We need a refactoring that makes it easy to move a procedure from one module to another (possibly a new one).

For example, in a project where public procedures are systematically qualified with a module:

```vb
Private Sub Workbook_Open()
    'this handler will not run if macros are disabled, leaving the warning visible and the buttons invisible
    Macros.ToggleMacros True
    Macros.SetOrderDate Now
End Sub
```

Manually moving, say, the `SetOrderDate` macro to a module other than `Macros` would break all call sites.

We need a refactoring that allows selecting a member and move it to another module, *and automatically update the call site qualifiers*. For example moving the `SetOrderDate` macro to a new `OrderFormMacros` module would automatically update this `Workbook_Open` handler as follows:

```vb
Private Sub Workbook_Open()
    'this handler will not run if macros are disabled, leaving the warning visible and the buttons invisible
    Macros.ToggleMacros True
    OrderFormMacros.SetOrderDate Now
End Sub
```

### PR DESCRIPTION
**Pull request by BZngr**
Closes #3618 
Closes #2452

This PR introduces a `MoveMemberRefactoring` to allow users to select one or more Members, Constants, and/or Fields and move them to another module. 

This PR also introduces a `ConflictDetectionSession` capability that could represent a PR all on its own. The `ConflictDetectionSession` is intended to clear the path for multiple rename validations prior to rewriting.  `MoveMemberRefactoring` needed the conflict detection capabilities, so it is packaged here.  

And, finally...happy to report that every object instantiation in this PR is accomplished directly or indirectly by `CastleWindsor`.  Every dependency (or factory dependency) is constructor injected.  It has been too long in coming, but I am just now _starting_ to get my head wrapped around both the benefits and mechanics of using the DI container.  No doubt I still have much to learn.

I'll apologize in advance for the size of this (double) PR - it's huge.  It's been  two years in the making (this is probably the 3rd or 4th rewrite).  On a positive note...if we are looking forward to having RD bust through the 8K unit test threshold...'_this one gets it done_'.

`ConflictDetectionSession`:
1. Find conflicts for proposed renames, relocations, or new-to-be-inserted declarations.  
2. Generate a non-conflicting name based on the proposed rename, proposed new `Declaration`, or proposed `Declaration` relocation/move.
3. The `ConflictDetectionSession` provides conflict analysis for multiple Declaration identifier (and/or location changes) per session.  When checking for conflicts, it takes into account new names previously proposed within the session.
4. Improved conflict detection:  I scoured the MS-VBAL looking for every naming rule I could find - and applied them in the context of a rename.  Once merged, this class will allow the elimination of the conflict detection code and tests from the `DeclarationFinder`.  I've run the `ConflictDetectionSession` tests using the current `DeclarationFinder` conflict detection code.  In comparison to the `ConflictDetectionSession`, the `DeclarationFinder` code generates 39 false-positive/or missed conflict errors - so there is some improvement.

`MoveMemberRefactoring`:
1. Supports Move-Source Module (Source) Types: `StandardModule`, `ClassModule`, `UserForm` 
2. Supports Move-Destination Module (Destination) Types: `StandardModule` only. (`ClassModule` destinations would be a future enhancement)
3. The user can specify an existing or new module as the Destination.
4. The refactoring supports selection of Public/Private Constants, Public Fields, and Public/Private Members.
5. Property Let/Set/Get members are treated as 'all or none' when selected or involved in a move.
6. Module qualification is applied to all references of moved declarations (including references that previously did not have module qualification).
7. Selected Members and Constants with Private accessibility will be modified to have Public accessibility when required to maintain compilable code.  Unselected Members and Constants that are moved in a supporting role, retain their original Accessibility or the move is non-executable.
8. The current strategy does not support changing a Field's accessibility from Private to Public in order to support a move (avoids breaking a module's encapsulation of state).  Note: encapsulating the field might be an acceptable technique to broaden the number of supported use cases...but it would also seem best to wait and use the split refactoring architecture introduced by #5387 to leverage the `EncapsulateFieldRefactoring` to accomplish this.    
9. Although the user is not allowed to initiate this refactoring by selecting a Private Field, Private Fields supporting the move will be relocated along with the selected Declarations (e.g., Property backing Fields) if doing so does not result in un-compilable code.

The PR initially includes a single Move strategy: `MoveMemberToStandardModule.cs`.  The current design intends that future move scenario support (e.g., `ClassModule` Destinations) are accomplished by the addition of strategy classes.  Each strategy implements `IMoveMemberRefactoringStrategy` which includes `bool IsApplicable(MoveMemberModel model)`.  The strategy is expected to 'self-identify' as the applicable strategy for a given scenario by having `IsApplicable` return `true`.  The goal/expectation is that each strategy's scenario analysis  is sufficient to ensure that only one strategy ever returns IsApplicable == true.  Should a use case occur where more than one strategy self-identifies as 'applicable', my current thinking is that the refactoring request is not executed because the _correct_ strategy is indeterminate.  

.

### CODE REVIEW

**Comment by BZngr** [comment]
Merge after #5419

**Comment by BZngr** [comment]
MoveMemberOptimized

**Comment by BZngr** [comment]
I would like to close this PR in order to split and resubmit the functionality with two PRs.
 
1. A `ConflictDetectionSession` PR.  This would propose the `ConflictDetectionSession` capability and the associated removal of conflict detection code in the `DeclarationFinder`.
2. The current `MoveMember` PR would be then re-submitted after modified with the outcomes of the `ConflictDetectionSession` PR and PR #5452.

I am hoping that this is a better approach.  And, will make the review process easier if for no other reason than because each PR is 'one thing' and smaller than the combined PR currently in the queue.

I plan to leave this PR open for a couple more days to see if there are any dissenting votes to the above plan.  If there are no dissenting comments (or no comments at all) - I'll proceed as described above.

**Comment by retailcoder** [comment]
Whatever happened to this refactoring?

**Pull request closed without merging**
