### PR TITLE
Add access keys for settings window

### LINKED ISSUE #5408: Add access keys to settings window
**Justification**
I use keyboard shortcuts quite a bit. Allowing keyboard navigation in the settings window would be a welcome option to have.

**Description**
Add an `_` (underscore) to controls like CheckBox and Labels that have [Label.Target property](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.label.target?view=netframework-4.8) set assigns an access key and enables keyboard navigation.

### PR DESCRIPTION
**Pull request by IvenBach**
Close #5408. Access keys can be changed to match the pond hive mind preference.

The `SearchBox` control doesn't get focus with with the assigned access key. Need to figure out how to get it to work still.

### CODE REVIEW

**Comment by MDoerner** [comment]
Is this PR really still WIP as the label suggests?

**Comment by MDoerner** [comment]
@IvenBach Is this still WIP as the label suggests or can we merge this?

**Comment by IvenBach** [comment]
I *think* WIP can be removed. I need to review it this weekend to remember what I did to be certain.

**Comment by retailcoder** [comment]
I'd like this PR merged for the 2.5.1 release.

**Comment by MDoerner** [comment]
Putting this into the release will require some additional non-trivial translation work.

**Comment by retailcoder** [comment]
@MDoerner ok let's skip it then - the translations are good to go (a few CZ entries need attention, but nothing major)

**Comment by IvenBach** [comment]
Unintended close.

**Comment by IvenBach** [comment]
This PR will be blocked by my other resource migrations. Will return to this once those are finalized and merged.

**Pull request merged**
