### PR TITLE
Rewrite of EncapsulateField refactoring

### LINKED ISSUE #875: Wrap fields in private type
A module usually has its fields this way:

```
Private mFoo As Integer
Private mBar As Integer

Public Property Get Foo() As Integer
    Foo = mFoo
End Property

Public Property Get Bar() As Integer
    Bar = mBar
End Property
```

That works, but I prefer this:

```
Private Type TClassName
    Foo As Integer
    Bar As Integer
End Type

Private this As TClassName

Public Property Get Foo() As Integer
    Foo = this.Foo
End Property

Public Property Get Bar() As Integer
    Bar = this.Bar
End Property
```

Wrapping the private fields in a private type like this, eliminates the need for prefixes and makes the code cleaner, leaving only a single field in the class, which I like to name `this`.

Could be just me though. Thoughts?

### PR DESCRIPTION
**Pull request by BZngr**
Rewrites `EncapsulateField Refactoring` to allow selection/encapsulation of multiple fields and provide an option to wrap the encapsulated fields in a UserDefinedType.    Closes #875 

The design was based on the following thoughts/goals:
1. I wanted the user to have the ability to quickly encapsulate 1 or more fields without having to enter/modify anything.  To this end, the refactoring produces a validated conflict-free set of default identifiers that the user can accept as-is.  Consequently, after invoking the refactoring, the user can encapsulate all fields in a module with 2 mouse-clicks (SelectAll/OK).  3 clicks to wrap all fields in a private Type.
2. "What would Visual Studio do?": VS's encapsulate field refactoring does not give the user any 'naming' options.  The only choice provided to the user is to continue using the encapsulated variable locally...or not.  This refactoring is a bit more friendly.  The user is allowed to modify the provided Property Name and choose to encapsulate the field as Read Only.  That said...
3. "Naming is hard.  Renaming is easy":  To keep the GUI uncluttered, Renaming is required for the user to modify the backing field identifier or the wrapping `UserDefinedType `and its variable name.

Some examples what the GUI looks like at the moment:

EFGUI_1

EFGUI_2

EFGUI_3

EFGUI_4

EFGUI_5

EFGUI_6

### CODE REVIEW

**Comment by Hosch250** [comment]
The merger might want to consider squashing this considering the tremendous number of commits.

**Comment by BZngr** [comment]
I'm adding a sequence of GUI screen shots to help describe an important use case that I think would be very hard to tease out of the code.  The use case is: 

_User has several fields that he wants to encapsulate in a UDT, but doesn't encapsulate them all at once.  Or, the user adds a field to the module and invokes the refactoring after previously encapsulating all fields in a UDT._

This use case represents a sequence of encapsulations where the refactoring wants to offer up the previously generated UDT as the destination for the field(s) to encapsulate.  The UDT generated by the refactoring holds the object's state - so within the code the UDT instance is identified as "ObjectStateUDT".  The difficulty is that after the refactoring, the ObjectStateUDT looks like any other Private UDT declaration.

The fundamental issue is: how to handle Private UDT declarations found in the current module?  It is possible that the UDT was generated by a prior Encapsulate Field refactoring, or the UDT pre-existed any refactoring.  Even though the ObjectStateUDT has a particular naming convention, there is nothing to prevent the user from changing the name between refactorings.  (Note/Question: I was considering the use of an Annotation '@ObjectStateUDT to specifically identify the UDT generated by this refactoring.  Would this be an appropriate use of an Annotation?

EFGUI_21

Since the user 'checked' the "Wrap fields in a UDT" , and the refactoring detected an existing Private UDT in the module (`Type TTest`), it offers a combo box of UDT choices as shown below.  `TModule3` is the new UDT that would be introduced by the refactoring.  Note: if there are no pre-existing Private UDTs in the module, the combo box is not shown...the user will get the UDT Type and field generated by the refactoring.

EFGUI_22

The user chooses the generated ObjectStateUDT and encapsulates `someValue`.  

Now the user invokes the refactoring again and is considering encapsulating `TheTarget`.  Currently, if the refactoring can detect an existing UDT that matches the default name for the ObjectStateUDT it _would_ generate, it offers it as the first choice to the user.

EFGUI_23

The dropdown content though, now includes the pre-existing UDT's _and_ the ObjectStateUDT it would create if the user does not choose an existing UDT.  (see below)

EFGUI_24

For completeness, the screenshot below shows that if the User selects an existing UDT from the combo box, the UDT is removed from the list of 'encapsulatable' fields.  You can also see that in the `Preview` that `TheTarget` is now a member of `Type TTest`.  Note: the refactoring does not 're-encapsulate' any existing members if the user picks an existing UDT.  Only the fields selected to add to the UDT.

EFGUI_25

**Comment by retailcoder** [comment]
OMG this is totally my new favorite toy!

Made a few UI tweaks:

dialog

I'm thinking the UI could be further streamlined by using a datagrid instead of a listview, where a TextBoxColumn could allow data entry, and CheckBoxColumns could set selection and read-only status. Thoughts?

**Comment by retailcoder** [comment]
hold on a second, I lost the combobox!

**Comment by BZngr** [comment]
@retailcoder I like the space benefits gained by your placement of the command buttons.  And, I like the idea of placing all editable controls in a datagrid, one line per member.  In fact, the single-entry-line is where I started out.  

Full disclosure: when I started contributing to RD, I knew _absolutely nothing_ about WPF.  After a couple prior  PR run-ins with dialog tweaks and this PR, I believe I now know _next to nothing_ about WPF.  So, anything I advocate for (or against) regarding the UI/WPF should be heavily discounted.

In my efforts to implement all controls on a single line I ran into the following: 

1. I could not keep the contained text box (Property Name) data entry 'live' as refreshing the ListView (to update the associated validation icon in the data template) would lose the cursor position in the text box.
2. Avoiding/Deferring the ListView/Active Text box refresh (e.g., wait for a LostFocus event or similar) did not allow displaying the invalid icon (validation feedback) on the line in real-time.  This made for an awkward user interaction IMO.

Because of the above, I landed on the Master-Detail layout.  A benefit of this layout (perhaps the only one) is that there is room for validation error descriptions right next to where the user is editing the Property Name.

I'm not sure if the ListView issues I ran into would be applicable using a datagrid.  (Rather, applicable to a datagrid in the hands of someone with more WPF chops).  I'll see if I can get further than I did with the ListView.

I agree regarding the new toy...The UI turned out surprisingly fun to use.  `Select All/Wrap in Private Type/Unwrap/Wrap/Unwrap/DeSelectAll/SelectAll/Wrap` - watch the `Preview` cycle...all...day...long.

**Comment by retailcoder** [comment]
No worries, it's just UI tweaks, the functionality itself is just... perfect! I can push another commit tonight if you'd rather do something else than fight with xaml.. was going to do it but ran out of time and figured it would have to be for another day. I'm picturing something like we had in the defunct Extract Method dialog from v1.4, *eventually* with up/down buttons and drag & drop support for reordering the members.

**Comment by BZngr** [comment]
Sounds like you have very specific UI improvements in mind that would take me days to understand and complete (and that's being very generous).  So, yes - please go ahead and make any changes you like.

**Pull request merged**
