### PR TITLE
Disable this inspection

### PR DESCRIPTION
**Pull request by retailcoder**
...from the Code Inspections toolwindow :smile: 

image

Also disabled the treeview while inspections are running:

image

### CODE REVIEW

**Comment by ckuhn203** [comment]
Can it be re-enabled from there once it's been disabled?

**Comment by Vogel612** [comment]
@ckuhn203 how would you do that? After you disable the inspection it naturally doesn't show up in the inspection results after refreshing

**Comment by retailcoder** [comment]
@ckuhn203 nope, @Vogel612 is correct. Clicking 'disable this inspection' sets it to 'DoNotShow' and refreshes the results; to re-enable it you need to bring up the inspection settings from the options dialog.

**Comment by retailcoder** [comment]
What would be nice would be to be able to bring up the inspection settings from a button on the toolbar there.

**Pull request merged**
