### PR TITLE
Updated License.rtf

### PR DESCRIPTION
**Pull request by vvilliamperez**
#3815

### CODE REVIEW

**Comment by ThunderFrame** [comment]
Gosh, RTF is awful to review....

**Comment by rubberduck203** [comment]
Why are we updating the license? 
What has changed here?
I’m aware from my desk, can’t view this diff on mobile, and the commit message doesn’t really help.

**Comment by bclothier** [comment]
@rubberduck203 In the OP, it links to the #3815, which indicates there's a problem with how line breaks are handled in the RTF. AIUI, vvilliamperez cleaned it up. 

It doesn't help that RTF is hard to read as @ThunderFrame  noted but I am fairly certain it's not really a change in the verbatim, only the layout.

**Comment by rubberduck203** [comment]
Ahh. Okay. I’m sorry. I missed the link to the issue.

**Pull request merged**
