### PR TITLE
Version bump 2.5.9

### LINKED ISSUE #5773: Include a user-agent header for VersionCheck requests
I was looking at the HTTP logs for the website, and between browser sessions and bots every request that came from Rubberduck's VersionCheck comes in with an "unknown" user-agent:

rubberduckvba.com logs

(IP addresses wiped)

Not a high priority at all, but the VersionCheck feature including a "Rubberduck-{version}" user-agent header would be nice.

### PR DESCRIPTION
**Pull request by retailcoder**
* Fixes exception in version check service (closes #5773 / irrelevant since we're hitting GitHub API, not rubberduckvba.com)
* Bumps version to 2.5.9

### CODE REVIEW

**Comment by Vogel612** [comment]
Last time I did that, I remember there being more version strings to adjust... Is that really all of them?

**Comment by retailcoder** [comment]
I just followed the version bump wiki, works on my machine! 🫣

**Comment by BZngr** [comment]
In `Discord` you mentioned removing the version swapping script to the `development` folder.  I see that the script is still included in the PR.  Just commenting in the event you still intended to remove it.

**Comment by retailcoder** [comment]
> In `Discord` you mentioned removing the version swapping script added to the `development` folder.  I see that the script is still included in the PR.  Just commenting in the event you still intended to remove it.

Thanks for the reminder, I would have forgotten!

**Pull request merged**
