### PR TITLE
Bug fixes for the Code Inspection window

### LINKED ISSUE #5237: Code Inspection Window Horizontal scrollbar issue
Version 2.4.1.5105
OS: Microsoft Windows NT 6.1.7601 Service Pack 1, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.9126.2282
Host Executable: EXCEL.EXE

The horizontal scrollbar that has been recently added has a few issues.

Initially clicking on an item nudges the horizontal scroll a little so that the icons and start of the text are then hidden from view.

After using the scrollbar and collapsing a grouping, expanding it again makes the scrollbar default to the far right hand side.

### PR DESCRIPTION
**Pull request by glowingrunes**
Following my submission for #5135, some bugs were raised. These were:

1) Auto-scrolling when clicking a cell. This has now been fixed with an event handler which stops the RequestBringIntoView event from reaching the ScrollViewer.
2) "After using the scrollbar and collapsing a grouping, expanding it again makes the scrollbar default to the far right hand side" - instead of placing the ScrollViewer inside the DataGrid, I put the DataGrid inside the ScrollViewer. Now it's actually appearing in the correct place and no longer behaves erratically.

Closes #5237.

### CODE REVIEW

**Comment by Vogel612** [comment]
this was based off of the state of `next` from 16 days ago and as such had some conflicts. You should update your local repository with the development progress to avoid things like this in the future ;)

**Comment by glowingrunes** [comment]
Whenever I do a pull in Visual Studio it says my "next" branch is up to date. And yet the latest commit I see when I View History is from 8th October? What am I doing wrong? I have run a Sync, Fetch and Pull on my "next" branch.

**Comment by retailcoder** [comment]
@glowingrunes you want to `git pull upstream next`, i.e. bring in the remote commits *from the main (this) repository*; when you do that the Team Explorer in VS should mention something about merge conflicts, and present a "merge" button - clicking it brings up the conflict resolution tooling.

**Comment by Vogel612** [comment]
@glowingrunes I think the issue is that you're only pulling from your fork of the codebase. You will need to add this repository here to the remotes available in your local git repository using something like:

```bash
git remote add upstream git@github.com:rubberduck-vba/Rubberduck.git
```

Then you can update your local repository's next by using:

```bash
# checkout next branch if not already on it
git checkout next 
git fetch upstream
git merge --ff-only upstream/next
```

**Comment by glowingrunes** [comment]
Ah, right. Thanks!

**Comment by glowingrunes** [comment]
Hmm, running into a problem when trying to fetch upstream.
```

A:\repos\Rubberduck>git fetch upstream
The authenticity of host 'github.com (140.82.118.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Warning: Permanently added 'github.com,140.82.118.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Vogel612** [comment]
do you have an SSH key registered with your github identity? If not you'll want to use the https cloning. You can accomplish that by changing the remote's url using 

```
git remote set-url upstream https://github.com/rubberduck-vba/Rubberduck.git
```

**Comment by glowingrunes** [comment]
Perfect, that fixed it. :)

**Comment by glowingrunes** [comment]
When I look at the AppVeyor build log, at the very bottom, it says:

C:\projects\rubberduck\Rubberduck.Core\UI\Inspections\InspectionResultsControl.xaml(246,14): error MC3015: The attached property 'DataGrid.RowDetailsTemplate' is not defined on 'Grid' or one of its base classes. [C:\projects\rubberduck\Rubberduck.Core\Rubberduck.Core.csproj]

But the solution builds fine for me in Visual Studio. Is there something I need to fix on my end? Was this to do with my `next` branch being out of date? I did resolve the merge conflicts. (Apologies for all the questions and thank you for all your help so far!)

**Comment by bclothier** [comment]
Normally, when I see a message like that, it implies that some files that should have been added, wasn't. Did you actually modify any other files besides the 2 files that PR shows? Maybe modified a behavior?

**Comment by glowingrunes** [comment]
Not that I'm aware of. When I added RequestIntoView to the GroupingGrid in InspectionResultsControl.xaml, it automatically created a new method and added it to the code behind. I don't think it modified anything else. I can double check once I'm back from holiday.

**Comment by glowingrunes** [comment]
Turns out there were more lines of code that weren't meant to be there, probably as a result of a cut and paste error, which was causing the invalid markup. D'oh! 🤦

**Pull request merged**
