### PR TITLE
Hotfix release for 2.3.0

### PR DESCRIPTION
**Pull request by retailcoder**

### CODE REVIEW

**Comment by retailcoder** [comment]
Blocked by #4621

**Comment by retailcoder** [comment]
[Draft release notes](https://github.com/rubberduck-vba/Rubberduck/releases/tag/untagged-cda2a0e96b1053cbaa53) completed

**Comment by rkapka** [comment]
The release notes page is not working for me (404).

**Comment by Vogel612** [comment]
The release notes are recorded in a draft release. Because the branch moved after the notes were initially created, the URL to these notes also changed. Could you check [this link](https://github.com/rubberduck-vba/Rubberduck/releases/edit/untagged-b5925ae561a9bfd0ea0f) for me?

If it doesn't work, I'll move the notes to a Discussion visible to all Members of the Rubberduck org

**Pull request merged**
