### PR TITLE
Create License

### PR DESCRIPTION
**Pull request by RaymondWise**
License information is included in the readme but no license file is included

### CODE REVIEW

**Comment by retailcoder** [comment]
@bclothier hmm I hadn't realized that GitHub would lose track of the repository's license by doing that.

**Comment by Hosch250** [comment]
Just add a file named "license" or "license.md" and GitHub will let you choose the template.

**Comment by Hosch250** [comment]
License file is here: https://github.com/rubberduck-vba/Rubberduck/blob/next/LICENSE

**Comment by retailcoder** [comment]
Thanks for the heads up! I'll have to decline the pull request though, since this is a sensitive file and I'm too lazy to diff it against the GPLv3 template (FWIW I trust you and I'm sure it's the vanilla file) - however as admin/owner I'd prefer it if I (or Chris) made the only commits to LICENSE.MD. Thank you for your understanding!

**Comment by RaymondWise** [comment]
@retailcoder Sure thing!

@bclothier I thought the copyright there is for the license itself, but I could be wrong.

**Pull request closed without merging**
