### PR TITLE
Close Issue 3507 run selected unit test

### LINKED ISSUE #3507: Possible to select which tests to run manually?
I have occasion to want to selectively run tests without running the whole batch.  Any way to tell RD which tests to run selectively?  Even a hack would do.  I don't want to comment out all the tests that I don't want to run if at all possible.

### PR DESCRIPTION
**Pull request by IvenBach**
Close #3507. Allows single test to be run.

Should this be expanded to include multiple selected tests?

### CODE REVIEW

**Comment by Vogel612** [comment]
I can find no reference to `RunSelectedTestCommand`. Is this F5 tested? If it is, did you forget to include a file?

Do note that the original intention of #3507 was to run selected test**s**. As such also the change to the i18n is an IMO incorrect change.  
So to answer the question: yes it should be expanded to include multiple tests :)

**Comment by retailcoder** [comment]
Hmm does the grid even *allow* for multiple selections (it should)?

**Comment by IvenBach** [comment]
It was F5 tested and was working. The grid does allow for multiple selections. Only the first test selected would run, even when multiple tests were selected.

**Comment by retailcoder** [comment]
@IvenBach seems like bad UX - wouldn't we want to run all the selected tests?

**Comment by IvenBach** [comment]
I only re-implemented what was already in RD. I'll have to refactor to get it to run all the selected tests.

**Pull request merged**
