### PR TITLE
potential fix for mouse lag

### PR DESCRIPTION
**Pull request by autoboosh**
It seems like the mouse hook was flooding the GUI with messages slowing everything down.

This proposed fix puts both the mouse as well as the keyboard hook each on a separate thread with their own message pumps. Only the filtered messages are then sent to the GUI thread for handling. This seems to fix the lagging issues.

There's still one remaining issue that I couldn't solve though. On Windows 10 64bit in all Office 2016 64bit products (Excel, Word, Access, ...) the keyboard hook does not work if started via rubberduck. It didn't work in the old version either. It does work however with Windows 7 64bit and Excel 2013 32bit. It also works if the keyboard hook is installed separately, that is, through a console app. Running the console app and then running Excel (or vice versa) works. Does anyone have an idea what the problem could be? Perhaps a newly added security model in Office 2016?

I'd also be grateful if anyone could review the code and point out any flaws.

Edit: What I forgot to mention is that Rubberduck does not start parsing automatically on startup anymore. The justification for this was that perhaps people with huge projects, > 300k LOC or the like, would prefer to have a working VBE before deciding to analyse their solution. I can revert that if requested.

### CODE REVIEW

**Comment by autoboosh** [comment]
Perhaps we should use the Raw Input API instead?

https://social.msdn.microsoft.com/Forums/vstudio/en-US/9dd73b4d-f89a-4b1e-bc8a-d5ee1a5a7d34/global-mouse-hooks-cause-mouse-lagging?forum=csharpgeneral

**Comment by autoboosh** [comment]
Here's a first draft of the mouse hook / keyboard replaced with raw input. This one actually works with Windows 10 / Office 2016, both 64bit.

Taken/adapted from http://www.codeproject.com/Articles/17123/Using-Raw-Input-from-C-to-handle-multiple-keyboard.

**Comment by autoboosh** [comment]
@ThunderFrame brought up a good point regarding malware applications which might flag Rubberduck as malicious because we use RawInput. Just as an aside...

**Comment by retailcoder** [comment]
@autoboosh @ThunderFrame very good point indeed. If it comes down to that then we'll add a note about it in the README, the wiki and the release notes - and when we're ready for a stable release we'll contact Symantec and others, and request to be white-listed.

As long as the "dangerous" API is internal, unexposed, and doesn't turn Rubberduck into a hook for actual malware to "extend" Rubberduck with features we don't intend to ever ship... at the end of the day if that  is what it takes to make our addin responsive *and* context-aware, then that's what it takes.

**Comment by autoboosh** [comment]
This should be mergable and seems to work. It's based on a project from CodeProject that's why I added a small attribution section to the README.

Does this version work on your PC @retailcoder and correctly detected keyboard/mouse changes?

Let me know if there are things left to correct.

**Pull request merged**
