### PR TITLE
MouseHook / CanExecute checks and selective reparse

### PR DESCRIPTION
**Pull request by retailcoder**
With this PR:

 - Everytime the current line changes in the active code pane, the parser engages a new parse task for that module
 - This means, for now, that arrow-navigation of the active code pane will trigger a reparse of the module
 - *Find all references* and *Find all implementations* commands are now tied to the active code pane; we need specific implementations for the Project Explorer and Code Explorer context menus, with a different `CanExecute` implementation that looks at the selected component, not the code pane selection.

Ref. #1201

### CODE REVIEW

**Comment by ThunderFrame** [comment]
AFAICT, when a procedure-level line has changed, VBE parses the changed line, then assesses whether to parse the containing procedure, then assesses whether to pass the module, then assesses whether to parse *other modules* or the entire project.

The rules would differ slightly for a changed line in the declarations section, and also if the line was inside an inactive branch of a compiler directive block.

Iirc, I don't think Rubberduck can initiate a parse at the procedural level, but maybe 2.x.

**Comment by retailcoder** [comment]
@ThunderFrame correct - we can only parse a whole module. When we can give the parser line offsets to create the declarations with, then we can start thinking about parsing arbitrary code. And then we'll need to pass a `CurrentScope` declaration to the resolver, and we'll be able to resolve on-demand (for a specific identifier reference) instead of walking all parse trees. But we're so not there yet.

**Comment by autoboosh** [comment]
What's the deal with changing the ICS_B_MemberCall precedence? Is that something that should be looked at / want me to have a look?

**Comment by retailcoder** [comment]
Remaining issues:

 - :boom: accessing the VBE object model (e.g. a `VBProject` or `VBComponent` object's properties) *from a background thread* happens to freeze up everything (except Rubberduck, ironically) and basically brick the VBE and the host app (needs to be killed with Task Manager).
 - :rage: a lot of `ICommand.CanExecute` implementations are doing the same thing: figure out what `Declaration` or `IdentifierReference` is selected in the code pane, to determine whether or not a command is enabled - this causes a noticeable lag when clicking. we need to somehow centralize that logic in one place, find the current "target" *once*, and somehow pass it to all commands that need it.

**Comment by retailcoder** [comment]
@Hosch250 because of the :boom: problem above, I'm not merging this PR just yet. If you want to work on the :rage: issue, feel free to branch off [next] in my own fork.

**Comment by retailcoder** [comment]
@Hosch250 commit e9f27660450dbb244994c1c919db5d29b9746458 sufficiently speeds up the context menu by moving some of the commands' `FindTarget` logic into the `RubberduckParserState` class (not sure that's the best ideal place to put that, but it was already a dependency used by all commands, with easy access to the declarations) - context menu lag is acceptable now.

that commit also removes the `KeyboardHook` (commented-out), due to what I deem serious threading issues (not your fault @Vogel612, it's really the rest of Rubberduck that wasn't meant to be called from a background STA thread), so instead I reinstated the 1.x-ish `ContentHashCode` check for modified modules, and configured a hotkey for refreshing parser state (Ctrl+`).

...and now 350-some tests are failing, and I need to sleep.

**Comment by retailcoder** [comment]
:see_no_evil: Fixed. :smiling_imp:  *Now* I can sleep.

**Pull request merged**
