### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by INOPIAE**
Removed "&" from the menue entries of the test explorer.
Removed obsolete entries from RubberduckUI

### CODE REVIEW

**Comment by ThunderFrame** [comment]
Aren't the ampersands for the keyboard shortcuts in VBE menus?

**Comment by INOPIAE** [comment]
Yes, but this does not seem to work for the test explorer. The ampersands were already removed in the English text. I just removed them for the other langugaes.

**Comment by retailcoder** [comment]
@ThunderFrame the ampersands don't work in WPF UI's; we may need to split the resource files to better tell what's used in COM controls (i.e. with ampersand) and what's not.

**Comment by ThunderFrame** [comment]
Yes, I hadn't inspected the code, had assumed it was the Test Explorer entries in the VBE menu, not the menu entries in the WPF window.

Is it an underscore, in WPF, if we're using Labels in the menus? Access keys are essential for Accessibility, so we should have them wherever possible.

**Pull request merged**
