### PR TITLE
Incorporate InspectionTestsBase progress - part 1

### PR DESCRIPTION
**Pull request by BZngr**
This PR incorporates `InspectionTestsBase` for Inspection unit test names beginning with the letters A thru E.  So...it is progress on #5191 - but not complete.  I thought I would generate a PR at this point of the process in case there were comments that would apply to the content of this PR as well as the next set of Inspection unit test updates.

### CODE REVIEW

**Comment by retailcoder** [comment]
Right? It's WIP?

**Comment by BZngr** [comment]
The PR can be merged As-Is unless you want to have all the inspections updated/done at one time.   I can work with either.  If you merge this one, the next PR will simply start with tests beginning with the letter F.

**Comment by bclothier** [comment]
FWIW, my vote would be to merge this PR as-is. Get more of it vetted by our ---QA team--- ---users--- developers actually running the tests.

**Comment by MDoerner** [comment]
@BZngr Have you already done more work to push to this PR? Otherwise, I would merge this and you could simply push the rest of the refactoring of inspection tests to a new PR.

**Comment by BZngr** [comment]
@MDoerner My most recent Sync now updates tests A thru H.  My preference would be to merge this PR and follow up with an additional PR(s) as well.

**Pull request merged**
