### PR TITLE
Add a Windows menu fixes #5505

### LINKED ISSUE #5505: Add a Windows menu
**Justification**
Increased discoverability of Rubberduck features.

**Description**
Currently, the various Rubberduck windows are accessible from many different locations. We should additionally provide a central collection of them, in the form of a `Windows` submenu from the RD main menu.

Resharper follows this (common?) design pattern:
image

The above entries are all available from other routes (including from other places on the ReSharper main menu), but having them all collected in one menu provides a quick answer to the questions, "What windows are available?" and "How do I open the window for {x}?". The duplication is justified by the added value.

### PR DESCRIPTION
**Pull request by INOPIAE**

### CODE REVIEW

**Comment by Vogel612** [comment]
IINM the RegEx assistant is also a separate window. There might be more windows that have been missed in the original issue.

**Comment by retailcoder** [comment]
Isn't it a dialog? I'm pretty sure the regex assistant is a dialog. Do we mean to only list the dockable toolwindows here?

**Comment by INOPIAE** [comment]
I would only take the dockable windows not the dialogs.

**Comment by Vogel612** [comment]
All the window classes that implement `IDockableUserControl` are:

- InspectionResults
- CodeMetrics
- CodeExplorer
- ToDoExplorer
- SearchResults
- TestExplorer

**Comment by INOPIAE** [comment]
Any specific order or just alphabetical?

**Comment by retailcoder** [comment]
I'd make it alphabetical tbh

**Review by retailcoder — APPROVED** [review]

**Pull request merged**
