### PR TITLE
add comments to parse tree

### PR DESCRIPTION
**Pull request by autoboosh**
Hacked together a solution for adding comments to the parse tree. Includes a CommentListener that saves all comments for later use. The CommentExtensions class strips the comments from useless tokens (didn't manage to do that directly in the grammar).

Please have a look and tell me if something's wrong.

### CODE REVIEW

**Comment by retailcoder** [comment]
Comments still end up in the parser state via the manual `ParseComments` method right? We'll need to deprecate the `CommentNode` API, but there are implications... can't remember off the top of my head, but *something* will break - awesome work you got here though! That's one long-standing limitation we had with this grammar all along!

**Comment by autoboosh** [comment]
I didn't touch the existing manual comment parsing code, so that's still the same. It seemed like a good idea to do this step by step, since it changes quite a lot.

Maybe we could keep the existing CommentNode and simply remove the parsing code? I haven't look too deeply at where/how the comments are used right now tbh.

**Comment by autoboosh** [comment]
Replaced the comment parsing logic with the parse tree nodes. The TODOs, annotations and the obsolete comment inspection seem to work fine from what I can see.

There was a comment about how line continuations are ignored in comments. They aren't ignored in this version anymore, hope that's OK.

**Comment by retailcoder** [comment]
I'm pulling this PR into a new local branch for some testing first. Fingers crossed!

**Comment by retailcoder** [comment]
Ah, I see what you did here...

    private IEnumerable<CommentNode> ParseComments(QualifiedModuleName qualifiedName, IEnumerable<VBAParser.CommentContext> comments, IEnumerable<VBAParser.RemCommentContext> remComments)
    {
        var commentNodes = comments
            .Select(comment => new CommentNode(comment.GetComment(), Tokens.CommentMarker, new QualifiedSelection(qualifiedName, comment.GetSelection())));
        var remCommentNodes = remComments
            .Select(comment => new CommentNode(comment.GetComment(), Tokens.Rem, new QualifiedSelection(qualifiedName, comment.GetSelection())));
        var allCommentNodes = commentNodes.Union(remCommentNodes);
        return allCommentNodes;
    }

You know what, I can live with that for 2.0; we can fine-tune the thing and get rid of `CommentNode` for 2.1 or something.

**Pull request merged**
