### PR TITLE
Consolidate resource cleanup

### LINKED ISSUE #4541: .resx needs a clean-up
There are a number of resource strings that were copied from the old `RubberduckUI.resx` file and into smaller, more specialized & manageable, namespaced resource files - but remained in their original location, resulting in duplicate keys.

There are also a number of duplicate resource strings *under different keys*, that should probably be consolidated.

Basically, string resources need a clean-up.

### PR DESCRIPTION
**Pull request by IvenBach**
All separate branches were merged into this one.

Issue Close #4541
Individual PR: Close #5622, Close #5621, Close #5620, Close #5619, Close #5618.

### CODE REVIEW

**Comment by IvenBach** [comment]
Close #5408 since it's related.

**Review by retailcoder — CHANGES_REQUESTED** [review]
I hope this doesn't throw a major wrench into this PR because I'd really like this to be merged as early as possible in 2.5.2.x, but the new `.it.resx` Italian resources should be in this diff, no?

**Comment by IvenBach** [comment]
Known conflicts have been resolved. Once this is merged it will permit me to move onto the next domino/PR #5731 and resolve it.

**Review by retailcoder — APPROVED** [review]

**Comment by Vogel612** [comment]
CC @retailcoder this MR caused #5857 due to an / some incorrect merging in Rubberduck.Core.csproj

**Pull request merged**
