### PR TITLE
Speed up parsers

### PR DESCRIPTION
**Pull request by autoboosh**
Changes:
1. Add support for foreign identifiers (#1521). Only the first "level" is considered and simply treated as a normal identifier.
2. Speed up all parsers by rewriting the grammar (#1502). The 65k comments example parses in 400ms here. The parser tests run in 2secs now. The preprocessor tests in 1sec. Modules in smaller test projects are usually parsed in <100ms. If the faster approach fails, it falls back automatically to the slower approach. This way even if there's a combination that requires the slow approach it won't fail. It does get logged however so we can fix it (currently simply using Debug.WriteLine).
3. Integrated expressions into the main grammar. There's no separate expression grammar anymore. Because of that valueStmt and rules like "implicitCallStmt_InStmt" are no more. There's no need (in most cases) to reparse expressions anymore either.

Please review and test with as much code as possible. All tests pass but since quite a few things have changed there might be some subtle things I've missed.

### CODE REVIEW

**Comment by retailcoder** [comment]
Awesome work!! Only missing #1539 with block resolution and we'll be good for a beta I think.

**Comment by autoboosh** [comment]
With block resolution should actually already work. Can you tell me what exactly doesn't work?

What I forgot to mention is that identifier references are now added even if part of an expression fails.

**Comment by retailcoder** [comment]
Oh sweet! I'll only be able to pull and test things later though, but this is looking very very very good!

**Comment by autoboosh** [comment]
No problem! Please tell me how long the parser/preprocessor tests take on your system. I wonder how long they take on @grleachman's PC. Hopefully under 1 minute...

**Pull request merged**
