### PR TITLE
Updated Sdk for VS 2019 compatibility. Fixes #4872

### LINKED ISSUE #4872: This repo fails to build/load in Visual Studio 2019
I got a report of a failure to build this repo, so I wanted to make y'all aware of the problem.

If you try to load `Rubberduck.sln` (or any individual project) in Visual Studio 2019 (Preview), it will fail. This is because `Sunburst.NET.Sdk.WPF/1.0.47` isn't compatible with 2019. From SunburstApps/MSBuildSdks#1, it sounds like Rubberduck should consider migrating to a different approach.

As mentioned there, one option is to wait for .NET Core 3.0 and its associated SDK, which [will support WPF projects](https://devblogs.microsoft.com/dotnet/net-core-3-and-support-for-windows-desktop-applications/). But that's not yet released.

### PR DESCRIPTION
**Pull request by 93Akkord**

### CODE REVIEW

**Comment by bclothier** [comment]
Nice! Is this also 2017-compatible? 

In case you didn't see, we also have [an open PR which is currently blocked due to a bug in WPF](Initial version using newest SDK supporting WinForms & WPF) in 16.4 build. Is this affected by this bug? 

Does the patch enable designers to work again? The plan was to return to the SDK once they fix the bug in the 16.4 build because it had better designer support.

**Comment by 93Akkord** [comment]
> Nice! Is this also 2017-compatible?
> 
> In case you didn't see, we also have [an open PR which is currently blocked due to a bug in WPF](https://github.com/rubberduck-vba/Rubberduck/pull/5239) in 16.4 build. Is this affected by this bug?
> 
> Does the patch enable designers to work again? The plan was to return to the SDK once they fix the bug in the 16.4 build because it had better designer support.

Sorry, I don't have 2017 on my machine right now to test.  If someone can clone my fork and test, that would be great!

In regards to the other PR.. I only noticed it after submitting this one :pensive:.

**Comment by Vogel612** [comment]
@bclothier @93Akkord as it stands, this does not adapt the appveyor.yml, so the passing CI implies that it should be straightforwardly built for VS 2017. 

Note that this PR "only" changes the SDK to a patched version of Sunburst instead of fully commiting to the Microsoft SDKs. That means the Sunburst SDK does not prevent building with VS2019 any more while preserving compat for VS2017.

The original problem with upgrading the SDK came from the "either-or" situation. As such I would like this PR to be merged (and possibly submit a minor expansion later to make appveyor build both the VS2019 and the VS2017 image). Note that the source of this new patched SDK is [ForNeVeR/MSBuildSdks](https://github.com/ForNeVeR/MSBuildSdks/tree/master/src/Sunburst.NET.Sdk.WPF) instead of [SunburstApps/MSBuildSdks](https://github.com/SunburstApps/MSBuildSdks).

**Comment by 93Akkord** [comment]
> @bclothier @93Akkord as it stands, this does not adapt the appveyor.yml, so the passing CI implies that it should be straightforwardly built for VS 2017.
> 
> Note that this PR "only" changes the SDK to a patched version of Sunburst instead of fully commiting to the Microsoft SDKs. That means the Sunburst SDK does not prevent building with VS2019 any more while preserving compat for VS2017.
> 
> The original problem with upgrading the SDK came from the "either-or" situation. As such I would like this PR to be merged (and possibly submit a minor expansion later to make appveyor build both the VS2019 and the VS2017 image). Note that the source of this new patched SDK is [ForNeVeR/MSBuildSdks](https://github.com/ForNeVeR/MSBuildSdks/tree/master/src/Sunburst.NET.Sdk.WPF) instead of [SunburstApps/MSBuildSdks](https://github.com/SunburstApps/MSBuildSdks).

For future reference would changing the below in appveyor.yml build both VS2017 and VS2019?

```yaml
# build-matrix: all Release CPUs on VS2017
image: Visual Studio 2019
configuration: Release
platform: Any CPU
```
to

```yaml
# build-matrix: all Release CPUs on VS2017 and VS2019
image:
  - Visual Studio 2017
  - Visual Studio 2019
configuration: Release
platform: Any CPU
```

**Comment by Vogel612** [comment]
@93Akkord from what I can tell, yes. I can't guarantee that the VS2019 image builds properly, though. We're using partially custom written workflows to support per-user registration of COM dlls, which could be a source of instability. 

An additional source of instability might be the recently introduced use of UNIX core utilities to upload coverage data, because the VS2019 image has WSL enabled by default, which could lead to shadowing...

**Comment by bclothier** [comment]
From what I observed, the workflow do work in 2019, so it's not the reason why it's failing. It does build locally on VS 2019 but not on 16.4 because of that bug linked. The main difference between Sunburst SDK and the WPF/WinForm SDK is supposedly that the latter has better designer & auto-codegen support. If the patched Sunburst SDK provides the same level of compatibility, especially for auto codegen, I'm content to stay with the patched Sunburst SDK. 

For references - auto codegen seem to not work with globbing; if you look in `Rubberduck.Resources`, you'll see there's both a globbing entry and explicit entry for each resource file. That becomes unnecessary with the proper WPF/WinForm SDK. 

Thanks again for the awesome contribution, @93Akkord!

**Pull request merged**
