### PR TITLE
Adding support for AutoCAD

### PR DESCRIPTION
**Pull request by mhredmond21**
Adding support for AutoCAD

### CODE REVIEW

**Comment by retailcoder** [comment]
Awesome! Note that I (/we) will not have a way of verifying whether the `RunMacro` call actually works; please confirm the following:

 - Unit tests run as expected with one test module.
 - Unit tests run as expected with two test modules, each with identical test names.

If the first one works, second should work too; this generates calls looking like this:

    Application.RunMacro "TestModule1.TestMethod1"

This format works in Excel, but not in Word for example.

If fully-qualified calls don't work, AutoCAD will not like having two test methods named `TestMethod1`, and the `TestInitialize` and `TestCleanup` method calls won't work either.

Otherwise, you've just enabled Rubberduck unit testing in AutoCAD! Thanks a million!

(@Hosch250 we can fix the indentation, but not the `RunMacro` call :wink:)

:+1:

**Comment by retailcoder** [comment]
Rubberduck adds `Option Private Module` to test modules, so test methods aren't exposed as macros in the host app; it *might* interfere with `RunMacro`.

If it does, we will just change the module template to not include that option when the host is AutoCAD.

**Comment by ckuhn203** [comment]
This is.. fantastic. I've been wanting to add this, but couldn't. Thank you!

**Comment by mhredmond21** [comment]
I have a problem, that the AutoCAD does not consider itself "BuiltIn". 

The following is from this class: public static IHostApplication HostApplication(this VBE vbe)


The code was:

            foreach (var reference in vbe.ActiveVBProject.References.Cast<Reference>()
                .Where(reference => (reference.BuiltIn && reference.Name != "VBA")))

I changed it to this and it works:

oreach (var reference in vbe.ActiveVBProject.References.Cast<Reference>()
                .Where(reference => (reference.BuiltIn && reference.Name != "VBA") || (reference.Name == "AutoCAD")))

However I think there may be a better way???

**Comment by retailcoder** [comment]
*Unknown* should be for tests that did not run... but then they have the icon of tests that passed... this isn't normal. But if there was a problem with COM interop they would have definitely failed.

Sync the PR, I'll see if there's a better way to special-case the host app.

**Comment by ckuhn203** [comment]
Okay. I remember what that extension method does now. If you open the editor in an Office app, and then open the References window, you'll see two references checked (assuming a brand new project). One is the VBA standard library, the other is the reference to the host application's object model. This extension allows us to determine what the application host is dynamically, and works *okay* for Office. There is an edge case where you have an Access host referencing the Excel object model for example. (*Boom!*). 

I don't particularly like this solution either, but generally speaking, it works. 

In an idea world, we would find a more reliable way to figure out what the Host Application is, so that we can instantiate the correct subclass of `HostApplication`. This extension is really just a factory, so I think it's *ok* as it is. (Minus the terrible kaboom edge case I just noticed and take 100% blame for.)

I do wonder if the line shouldn't be `((reference.BuiltIn || reference.Name == "AutoCAD") && reference.Name != "VBA")` though. Does AutoCad automatically add a reference to the VBA standard library?

As for needing to add the check here, maybe there's some reflection magic we could do, but that seems like overkill to me. The number of possible hosts is limited.

**Comment by ckuhn203** [comment]
Never mind the suggested code change. I just saw that it was equivalent to what you wrote.

**Comment by ThunderFrame** [comment]
Inspecting the 2nd reference does mostly tell you the host application. There are 3 other ways that I know of.

 1. Use a VbProject hwnd to find the processID, then determine/get the host from the pid.

 2.  If the VbProject has at least 1 document-type module (eg. Workbook, Access Report, Stencil) then you can read the VbComponent properties to get back to the host object.

3. Last resort, inspect the code for object hints, like DoCmd, ActiveWorkbook, etc.

**Pull request merged**
