### PR TITLE
Testing PR builds in AppVeyor

### PR DESCRIPTION
**Pull request by FeodorFitsner**

### CODE REVIEW

**Comment by retailcoder** [comment]
I can see the GitHub webhook firing and receiving a 204 OK response, but on the AppVeyor side there's no event, and nothing happening.

**Comment by FeodorFitsner** [comment]
OK, thanks for letting know. That webhook is ignored when GitHub is authorized as an App.

However, it looks like we've found the issue. We'll take a deeper look at what's going on and deploy a bug fix later today. Thanks for your patience! I'll provide an update here.

**Comment by FeodorFitsner** [comment]
We've deployed AppVeyor update with a fix. I've been able to start a new build of my test PR: https://ci.appveyor.com/project/rubberduck-vba-releasebot/rubberduck/history

Well, you have to close/open this PR again to start a new build.

**Comment by Vogel612** [comment]
@FeodorFitsner Thanks for the help :+1:

**Comment by FeodorFitsner** [comment]
Sure, glad it works again!

**Pull request closed without merging**
