### PR TITLE
German translations for Inspections

### PR DESCRIPTION
**Pull request by Imh0t3b**
DeclareAsExplicitVariantQuickFix, EmptyCaseBlockInspectionResultFormat, EmptyCaseBlockInspectionName, EmptyCaseBlockInspectionMeta

### CODE REVIEW

**Comment by Imh0t3b** [comment]
missed #3478

**Comment by retailcoder** [comment]
@Imh0t3b no need to reject the PR - just push extra commits, the PR will synchronize automatically :smile:

**Comment by retailcoder** [comment]
*clicks link to #3478* ..whoops.

**Comment by Imh0t3b** [comment]
sorry newbie. First cancelt unnecessary, then reverted the revert of revert of ..
I'll improve, reverted reverts sure can be merged to nothing. I blame vogel612 :grin:, he provided the false link #3479 instead of #3478!.... Just kinding, I don't, thanks for your help :yellow_heart:

**Pull request closed without merging**
